function out = task7_write_report(outDir)
%TASK7_WRITE_REPORT Generate a self-contained report (HTML, optionally PDF).
%   out = task7_write_report(outDir) creates a publishable MATLAB script inside
%   outDir, then runs publish() to generate HTML. It also tries to generate
%   PDF (may require LaTeX tooling); if PDF fails, HTML is still produced.
%
%   Returns struct with fields:
%     - reportScript
%     - htmlPath (if generated)
%     - pdfPath (if generated)

if nargin < 1 || isempty(outDir)
    error('outDir is required');
end

outDir = char(outDir);
if ~exist(outDir, 'dir')
    error('Output directory does not exist: %s', outDir);
end

reportScript = fullfile(outDir, 'task7_report_publish.m');

lines = {};

% Build publishable script
lines{end+1} = "%% UMINT (2026) - Zadanie 7: MLP vs CNN (MNIST)";
lines{end+1} = "% Auto-generated by task7_write_report.m";
lines{end+1} = "thisDir = fileparts(mfilename('fullpath'));";
lines{end+1} = "figDir = fullfile(thisDir, 'figures');";
lines{end+1} = "";

lines{end+1} = "%% Loaded results";
lines{end+1} = "load(fullfile(thisDir,'mlp_results.mat'),'mlp_results');";
lines{end+1} = "load(fullfile(thisDir,'cnn_results.mat'),'cnn_results');";
lines{end+1} = "disp('Loaded mlp_results and cnn_results.');";
lines{end+1} = "";

lines{end+1} = "%% MLP - Hyperparameters (Table 1)";
lines{end+1} = "t = readtable(fullfile(thisDir,'table1_mlp_models_hyperparams.csv'));";
lines{end+1} = "disp(t);";
lines{end+1} = "";

lines{end+1} = "%% MLP - 5 runs per structure (Tables 2-3)";
lines{end+1} = "files = dir(fullfile(thisDir,'table2_3_mlp_runs_*.csv'));";
lines{end+1} = "for i = 1:numel(files)";
lines{end+1} = "    fprintf('\\n-- %s --\\n', files(i).name);";
lines{end+1} = "    t = readtable(fullfile(thisDir, files(i).name));";
lines{end+1} = "    disp(t);";
lines{end+1} = "end";
lines{end+1} = "";

lines{end+1} = "%% MLP - Summary (Table 4)";
lines{end+1} = "t = readtable(fullfile(thisDir,'table4_mlp_summary.csv'));";
lines{end+1} = "disp(t);";
lines{end+1} = "";

lines{end+1} = "%% CNN - Hyperparameters (Table 5)";
lines{end+1} = "t = readtable(fullfile(thisDir,'table5_cnn_models_hyperparams.csv'));";
lines{end+1} = "disp(t);";
lines{end+1} = "";

lines{end+1} = "%% CNN - 5 runs per architecture (Tables 6-8)";
lines{end+1} = "files = dir(fullfile(thisDir,'table6_8_cnn_runs_*.csv'));";
lines{end+1} = "for i = 1:numel(files)";
lines{end+1} = "    fprintf('\\n-- %s --\\n', files(i).name);";
lines{end+1} = "    t = readtable(fullfile(thisDir, files(i).name));";
lines{end+1} = "    disp(t);";
lines{end+1} = "end";
lines{end+1} = "";

lines{end+1} = "%% CNN - Summary (Table 9)";
lines{end+1} = "t = readtable(fullfile(thisDir,'table9_cnn_summary.csv'));";
lines{end+1} = "disp(t);";
lines{end+1} = "";

lines{end+1} = "%% Dropout analysis (Tables 10-11)";
lines{end+1} = "t10 = readtable(fullfile(thisDir,'table10_dropout_overfit.csv'));";
lines{end+1} = "t11 = readtable(fullfile(thisDir,'table11_dropout_mean_summary.csv'));";
lines{end+1} = "disp(t10);";
lines{end+1} = "disp(t11);";
lines{end+1} = "";

lines{end+1} = "%% MLP vs CNN comparison (Table 12)";
lines{end+1} = "t = readtable(fullfile(thisDir,'table12_mlp_vs_cnn.csv'));";
lines{end+1} = "disp(t);";
lines{end+1} = "";

lines{end+1} = "%% CPU vs GPU timing (Table 13)";
lines{end+1} = "t = readtable(fullfile(thisDir,'table13_cpu_vs_gpu.csv'));";
lines{end+1} = "disp(t);";
lines{end+1} = "";

lines{end+1} = "%% Figures";
lines{end+1} = "if exist(figDir,'dir')";
lines{end+1} = "    imgs = dir(fullfile(figDir,'*.png'));";
lines{end+1} = "    for i = 1:numel(imgs)";
lines{end+1} = "        p = fullfile(figDir, imgs(i).name);";
lines{end+1} = "        try";
lines{end+1} = "            I = imread(p);";
lines{end+1} = "            figure('Name', imgs(i).name);";
lines{end+1} = "            image(I);";
lines{end+1} = "            axis image off;";
lines{end+1} = "            title(strrep(imgs(i).name,'_','\\_'));";
lines{end+1} = "        catch ME";
lines{end+1} = "            fprintf('Could not render %s: %s\\n', imgs(i).name, ME.message);";
lines{end+1} = "        end";
lines{end+1} = "    end";
lines{end+1} = "else";
lines{end+1} = "    disp('No figures folder found.');";
lines{end+1} = "end";

% Write script file
fid = fopen(reportScript, 'w');
if fid < 0
    error('Failed to create report script: %s', reportScript);
end
cleaner = onCleanup(@() fclose(fid));
for i = 1:numel(lines)
    fprintf(fid, '%s\n', lines{i});
end
clear cleaner;

out = struct();
out.reportScript = reportScript;
out.htmlPath = '';
out.pdfPath = '';

% publish() executes the script when evalCode is true (default). For that,
% the script must be on the MATLAB path.
addedToPath = false;
if isempty(strfind(path, outDir)) %#ok<STREMP>
    addpath(outDir);
    addedToPath = true;
end
pathCleaner = onCleanup(@() local_cleanup_path(outDir, addedToPath));

% Some MATLAB versions require the file to be resolvable by name (not only by
% absolute path) when evalCode=true. Switch into outDir and publish by name.
prevDir = pwd;
cd(outDir);
cdCleaner = onCleanup(@() local_cleanup_cd(prevDir));

% Publish HTML
opts = struct();
opts.format = 'html';
opts.outputDir = outDir;
opts.showCode = false;
opts.useNewFigure = true;
opts.maxOutputLines = 2000;

publish('task7_report_publish.m', opts);
htmlPath = fullfile(outDir, 'task7_report_publish.html');
if exist(htmlPath, 'file')
    out.htmlPath = htmlPath;
end

% Try publish PDF (may require LaTeX)
try
    optsPdf = opts;
    optsPdf.format = 'pdf';
    publish('task7_report_publish.m', optsPdf);
    pdfPath = fullfile(outDir, 'task7_report_publish.pdf');
    if exist(pdfPath, 'file')
        out.pdfPath = pdfPath;
    end
catch
    % Ignore PDF failure; HTML is enough.
end

clear cdCleaner pathCleaner;

end

function local_cleanup_cd(prevDir)
try
    cd(prevDir);
catch
end
end

function local_cleanup_path(outDir, addedToPath)
if addedToPath
    try
        rmpath(outDir);
    catch
    end
end
end
